# Generated by Django 3.1.3 on 2021-02-17 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddToCart',
        ),
    ]
