SUCCESS_RESPONSE_CREATED = 201
SUCCESS_RESPONSE_CODE = 200
METHOD_NOT_ALLOWED = 405
UNAUTHORIZED = 401
PAGE_NOT_FOUND = 404
INTERNAL_SERVER_ERROR = 500
BAD_REQUEST_CODE = 400

# User Roles
DRIVER_ROLE = 'DRIVER'
SELLER_ROLE = 'SELLER'
BUYER_ROLE = 'BUYER'

DOMAIN_MEDIA_URL = 'http://dev.kwkdrop.com'

FORGOT_PASSWORD_KEY_LENGTH = 6
FORGOT_PASSWORD_KEY_VALIDITY_IN_MINUTES = 10

DEFAULT_PROFILE_IMAGE = "https://kwkdrop.s3-us-east-2.amazonaws.com/media/1_LK4H69l.jpg"