# Generated by Django 3.0.4 on 2021-03-09 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authModule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.TextField(db_column='address', default=''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_set_password',
            field=models.BooleanField(db_column='is_set_password', default=False),
        ),
        migrations.CreateModel(
            name='ResetPassword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_column='email', default='', max_length=50)),
                ('verification_code', models.CharField(db_column='verification_code', default='', max_length=6)),
                ('user', models.OneToOneField(db_column='user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ResetPassword',
            },
        ),
    ]
