# Generated by Django 3.0.4 on 2021-03-09 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authModule', '0002_auto_20210309_1230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resetpassword',
            name='email',
        ),
        migrations.AddField(
            model_name='resetpassword',
            name='key_expires',
            field=models.DateTimeField(default='2021-03-09 13:09:04'),
        ),
    ]
