# Generated by Django 3.0.4 on 2021-03-09 11:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authModule', '0004_auto_20210309_1317'),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_state', models.TextField(db_column='license_state', default='')),
                ('license_number', models.BigIntegerField(db_column='license_number', default=0)),
                ('license_exp_date', models.TextField(db_column='license_exp_date', default='')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.TextField(db_column='vehicle_type', default='')),
                ('vehicle_make', models.TextField(db_column='vehicle_make', default='')),
                ('vehicle_number', models.TextField(db_column='vehicle_number', default='')),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.CharField(db_column='date_of_birth', default='', max_length=15),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.BigIntegerField(db_column='phone_number', default=0),
        ),
        migrations.AlterField(
            model_name='resetpassword',
            name='key_expires',
            field=models.DateTimeField(db_column='key_expires', default=datetime.datetime.now),
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_security_number', models.BigIntegerField(db_column='social_security_number', default=0)),
                ('license', models.OneToOneField(db_column='license', on_delete=django.db.models.deletion.CASCADE, to='authModule.License')),
                ('profile', models.OneToOneField(db_column='profile', on_delete=django.db.models.deletion.CASCADE, to='authModule.UserProfile')),
                ('user', models.OneToOneField(db_column='user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.OneToOneField(db_column='vehicle', on_delete=django.db.models.deletion.CASCADE, to='authModule.Vehicle')),
            ],
        ),
    ]
