# Generated by Django 3.0.4 on 2021-03-09 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authModule', '0005_auto_20210309_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='role',
            field=models.OneToOneField(db_column='role', default='', on_delete=django.db.models.deletion.CASCADE, to='authModule.UserRole'),
            preserve_default=False,
        ),
    ]
