# Generated by Django 3.0.4 on 2021-03-09 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authModule', '0006_driver_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_color',
            field=models.TextField(db_column='vehicle_color', default=''),
        ),
    ]
