# Generated by Django 3.0.4 on 2021-03-10 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authModule', '0007_vehicle_vehicle_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopHour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.TextField(db_column='day', default='')),
                ('open_time', models.TextField(db_column='open_time', default='')),
                ('close_time', models.TextField(db_column='close_time', default='')),
                ('is_24hours_open', models.BooleanField(db_column='is_24hours_open', default=False)),
                ('is_always_open', models.BooleanField(db_column='is_always_open', default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.OneToOneField(db_column='profile', on_delete=django.db.models.deletion.CASCADE, to='authModule.UserProfile')),
                ('role', models.OneToOneField(db_column='role', on_delete=django.db.models.deletion.CASCADE, to='authModule.UserRole')),
                ('shopHour', models.ForeignKey(db_column='shopHour', on_delete=django.db.models.deletion.CASCADE, to='authModule.ShopHour')),
                ('user', models.OneToOneField(db_column='user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
