# Generated by Django 3.0.4 on 2021-03-10 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authModule', '0008_seller_shophour'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='driver',
            table='Driver',
        ),
        migrations.AlterModelTable(
            name='seller',
            table='Seller',
        ),
        migrations.AlterModelTable(
            name='shophour',
            table='ShopHour',
        ),
        migrations.AlterModelTable(
            name='vehicle',
            table='Vehicle',
        ),
    ]
