# Generated by Django 3.0.4 on 2021-03-10 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authModule', '0009_auto_20210310_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='shopHour',
        ),
        migrations.AddField(
            model_name='shophour',
            name='user',
            field=models.ForeignKey(db_column='user', default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
