# Generated by Django 3.0.4 on 2021-03-10 11:18

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authModule', '0010_auto_20210310_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shophour',
            name='close_time',
        ),
        migrations.RemoveField(
            model_name='shophour',
            name='day',
        ),
        migrations.RemoveField(
            model_name='shophour',
            name='is_24hours_open',
        ),
        migrations.RemoveField(
            model_name='shophour',
            name='open_time',
        ),
        migrations.AddField(
            model_name='seller',
            name='shopHour',
            field=models.OneToOneField(db_column='shopHour', default='', on_delete=django.db.models.deletion.CASCADE, to='authModule.ShopHour'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shophour',
            name='week',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=''),
            preserve_default=False,
        ),
    ]
