# Generated by Django 3.0.4 on 2021-03-10 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authModule', '0011_auto_20210310_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shophour',
            name='user',
        ),
    ]
