# Generated by Django 3.0.4 on 2021-02-17 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='muser',
            table=None,
        ),
    ]
