# Generated by Django 3.0.4 on 2021-02-18 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0002_auto_20210217_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bagger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('role', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
