# Generated by Django 3.0.4 on 2021-02-23 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0006_auto_20210218_1844'),
    ]

    operations = [
        migrations.DeleteModel(
            name='mBagger',
        ),
    ]
