# Generated by Django 3.0.4 on 2021-02-23 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0007_delete_mbagger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muser',
            name='role',
            field=models.CharField(choices=[('D', 'Driver'), ('S', 'Seller'), ('B', 'Buyer')], max_length=20),
        ),
    ]
