# Generated by Django 3.0.4 on 2021-02-23 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0008_auto_20210223_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='muser',
            name='email',
            field=models.EmailField(default='null-mail', max_length=50),
        ),
        migrations.AddField(
            model_name='muser',
            name='phone',
            field=models.BigIntegerField(default=12345),
        ),
    ]
