# Generated by Django 3.0.4 on 2021-02-23 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0009_auto_20210223_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muser',
            name='role',
            field=models.CharField(choices=[(1, 'Driver'), (2, 'Seller'), (3, 'Buyer')], max_length=20),
        ),
    ]
