# Generated by Django 3.0.4 on 2021-02-24 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0011_auto_20210224_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='muserregistration',
            name='user',
        ),
        migrations.AddField(
            model_name='muserregistration',
            name='email',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='muserregistration',
            name='verification_code',
            field=models.IntegerField(default=0),
        ),
    ]
